name: "Basic Environment Setup"

on: [push, workflow_dispatch]

jobs:
  lsb_release:
    runs-on: [self-hosted, Ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: "Print Environment Info"
        run: |
          uname -a
          lsb_release --all

  # https://snapcraft.io/
  snap:
    runs-on: [self-hosted, Ubuntu]
    steps:
      - uses: actions/checkout@v3
      # https://github.com/ConorMacBride/install-package
      - uses: ConorMacBride/install-package@v1
        with:
          apt: snap
      - name: "Print Snap Version"
        run: snap --version
